<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTlp1dwh\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTlp1dwh/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerTlp1dwh.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerTlp1dwh\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerTlp1dwh\appProdProjectContainer([
    'container.build_hash' => 'Tlp1dwh',
    'container.build_id' => '6ef66f37',
    'container.build_time' => 1711305493,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTlp1dwh');
